### ISSUE TITLE
Filter out out of bound coordinates

### ISSUE THREAD

**Issue by analystcmyk** [ttnmapper/bugtracker#13]
Due to a decoding glitch / GPS error on of my trackers reported a LAT of -2587.

This results in a long strip of globes in an effort to draw the dot.

I would suggest automatically dropping any location outside Lat 90, -90 Lon 180-180

**Comment by jpmeijers** [comment]
Good one!

We have this filter in place for non-experimental data coming in from TTN v2:
https://github.com/ttnmapper/ingress-api/blob/a7b1273519ee9b990fd6191eef21e9d6025268ef/ttn/ttn_handlers.go#L84

But it is currently disabled for V3, because the new backend can still use these invalid coordinates to update gateway status:
https://github.com/ttnmapper/ingress-api/blob/a7b1273519ee9b990fd6191eef21e9d6025268ef/tts/tts_handlers.go#L159

As stated in the comment there we need to move the data validity check to just before inserting the data into the database, ie here:
https://github.com/ttnmapper/postgres-insert-raw/blob/ffac42a9fbb63d472673b69063da059931935f47/main.go#L275

**Comment by jpmeijers** [comment]
There was some logic that caused invalid data to end up in the database. This was fixed a couple of weeks ago. 

https://github.com/ttnmapper/ingress-api/commit/12559a6d634f71355432fe2bda938656725fd219
