### ISSUE TITLE
Data loss with zoom

### ISSUE THREAD

**Issue by mellbratt** [ttnmapper/bugtracker#3]
Looks odd when I view
<img width="2032" alt="screen shot 2018-07-09 at 11 05 44" src="https://user-images.githubusercontent.com/41116/42441366-416d8cb2-8368-11e8-98fe-cf2b8225b5e3.png">
and then zoom in by scrolling one step
<img width="2032" alt="screen shot 2018-07-09 at 11 05 56" src="https://user-images.githubusercontent.com/41116/42441373-467793f6-8368-11e8-9c12-36b3b2ce4888.png">
I expect to see the same measurements in both zoom levels.
Coordinates are 59.329920, 18.060384

**Comment by jpmeijers** [comment]
Wow, good catch. I think the problem here is that the gateway's own location isn't taken into account when checking if a gateway's coverage is currently visible in the current map bounding box. This is normally not an issue, but here it happens as mapped coverage is completely to the one side, and can fall outside of view even if the gateway is still visible.

Should be an easy fix.

**Comment by jpmeijers** [comment]
https://github.com/ttnmapper/gateway-bbox/commit/5e10212ecb42a87a6c4b956f26d73347eda84e99 addressed this issue
